language: python

python:
    - "2.7"

install:
    - pip install -e . -r ./requirements-dev.txt

before_script:
    - mkdir ~/.ngipipeline && cp test_ngi_config.yaml ~/.ngipipeline/ngi_config.yaml

script:
    - pytest --cov=ngi_pipeline ngi_pipeline/tests/

after_success:
  - codecov

notifications:
    email: false
